name: Test

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        activesupport: ['6.1', '7.0']
        ruby: ['2.6', '2.7', '3.0']
        exclude:
          - activesupport: '7.0'
            ruby: '2.6'
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
      env:
        ACTIVESUPPORT: ${{ matrix.activesupport }}
    - name: Rspec
      run: bundle exec rspec
